"""Route coverage — every expected route must be mounted.

When a P-section adds an endpoint, add it to EXPECTED_ROUTES below. A
failing test here is the early-warning signal that a router was
refactored without an expectation update.
"""
from __future__ import annotations

import importlib
from typing import Set

import pytest


EXPECTED_ROUTES: Set[tuple] = {
    # Web UI + memory (pre-refactor)
    ("GET",  "/"),
    ("GET",  "/missed-calls"),
    ("POST", "/chat"),

    # V7 — ops probes
    ("GET",  "/health"),
    ("GET",  "/ready"),

    # V3.12 — self-serve signup
    ("GET",  "/signup"),
    ("POST", "/signup"),

    ("POST", "/recover/{caller_id}"),
    ("GET",  "/memory/{caller_id}"),
    ("POST", "/memory/{caller_id}"),

    # Voice + SMS (Twilio webhooks)
    ("POST", "/voice/incoming"),
    ("POST", "/voice/setlang"),
    ("POST", "/voice/gather"),
    ("POST", "/voice/status"),
    ("POST", "/sms/incoming"),

    # Admin (P0, J, P7, P10, V4)
    ("GET",  "/admin"),
    ("GET",  "/admin/"),
    ("GET",  "/admin/calls"),
    ("GET",  "/admin/call/{call_sid}"),          # V4 — per-call detail
    ("GET",  "/admin/export.csv"),
    ("GET",  "/admin/flags"),
    ("GET",  "/admin/alerts/trigger"),
    ("GET",  "/admin/analytics"),
    ("GET",  "/admin/evals"),
    ("GET",  "/admin/bookings"),
    ("GET",  "/admin/agency/{agency_id}"),           # V3.9 — agency aggregate
    ("GET",  "/admin/live"),                         # V3.14 — live calls

    # Client portal (P1, V3 polish, V4 detail)
    ("GET",  "/client/{client_id}"),
    ("GET",  "/client/{client_id}/calls"),
    ("GET",  "/client/{client_id}/call/{call_sid}"),     # V4 — client-side detail
    ("GET",  "/client/{client_id}/invoice/{month}"),
}


_SWAGGER_PATHS = {"/docs", "/redoc", "/docs/oauth2-redirect"}


def _discover_routes() -> Set[tuple]:
    import main
    importlib.reload(main)
    found = set()
    for route in main.app.router.routes:
        methods = getattr(route, "methods", None) or set()
        path = getattr(route, "path", None)
        if not path or path.startswith("/openapi") or path in _SWAGGER_PATHS:
            continue
        for m in methods:
            if m in ("GET", "POST", "PUT", "DELETE", "PATCH"):
                found.add((m, path))
    return found


def test_every_expected_route_is_mounted():
    found = _discover_routes()
    missing = EXPECTED_ROUTES - found
    assert not missing, (
        f"Expected routes not found on app: {sorted(missing)}\n"
        f"If a route was intentionally removed, drop it from "
        f"EXPECTED_ROUTES in tests/test_routes.py."
    )


def test_no_unexpected_route_surface():
    """Catches the reverse: a new endpoint shipped without being added
    to EXPECTED_ROUTES. Forces the manifest to stay authoritative.

    We deliberately allow HEAD (auto-generated by FastAPI for GETs) —
    those aren't in the expected set but they aren't new surface area."""
    found = _discover_routes()
    unexpected = {r for r in found if r not in EXPECTED_ROUTES
                  and r[0] not in ("HEAD", "OPTIONS")}
    assert not unexpected, (
        f"Unexpected routes mounted: {sorted(unexpected)}\n"
        f"Add them to EXPECTED_ROUTES in tests/test_routes.py or "
        f"remove them from the app."
    )
